language: node_js
node_js:
  - "7"

cache: npm

script:
  - 

before_deploy:
  - npm install
  - hexo g

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./public
  target-branch: master
  on:
    branch: hexo

# vim: et:ts=2:sw=2:
